fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: '%env(MAILER_USER)%'
        sender_name: '%env(MAILER_NAME)%'
    resetting:
        email:
            from_email:
                address: '%env(MAILER_USER)%'
                sender_name: '%env(MAILER_NAME)%'
    service:
        mailer: 'fos_user.mailer.twig_swift'