twig:
    paths: 
        '%kernel.project_dir%/templates': Temp
        "%kernel.root_dir%/../templates": Templates
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@Templates/easy_admin/api_dashboard.html.twig'