#user
api_orders_availables:
    path: '/api/shipping-methods-available'
    methods: ['POST']
    defaults:
        _controller: App\Controller\OrderController::getAvailableShippingMethods
        _api_resource_class: App\Entity\Order
        _api_collection_operation_name: 'available'
