App\Entity\PriceList:
    attributes:
        id:
            groups: ['price-read',"product-read","attribute-read", "attributevalue-read","category-read", 'pricelist-read']
        name:
            groups: ['price-read',"product-read","attribute-read", "attributevalue-read","category-read", 'pricelist-read']
        title:
            groups: ['price-read',"product-read","attribute-read", "attributevalue-read","category-read", 'pricelist-read']
        description:
            groups: ['price-read',"product-read","attribute-read", "attributevalue-read","category-read", 'pricelist-read']
        value:
            groups: ['price-read',"product-read","attribute-read", "attributevalue-read", "category-read", 'pricelist-read']
        prices:
            groups: ['pricelist-read']