resources:
    App\Entity\Product:
        attributes:
            pagination_enabled: false
            normalization_context:
                groups: ['product-read']
            denormalization_context:
                groups: ['product-write']
        collectionOperations:
            
        itemOperations: