easy_admin:
    entities:    
        Contract:
            class: App\Entity\Contract
            label: menu.contracts
            list:
                title: menu.contracts
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'externalId', label: 'externalId' }
                    - { property: 'user', label: 'user' }
                    - { property: 'activationDate', label: 'activationDate' }

            show:
                title: menu.contract
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'externalId', label: 'externalId' }
                    - { property: 'phone', label: 'phone' }
                    - { property: 'mobilePhone', label: 'mobilePhone' }
                    - { property: 'iban', label: 'iban' }
                    - { property: 'email', label: 'email' }
                    - { property: 'status', label: 'status' }
                    - { property: 'user', label: 'user' }
                    - { property: 'dni', label: 'dni', type: 'image', base_path: '%env(CONTRACT_PATH)%%env(DNI_PATH)%' }
                    - { property: 'dniBack', label: 'dniBack', type: 'image', base_path: '%env(CONTRACT_PATH)%%env(DNI_BACK_PATH)%' }
                    - { property: 'supplyContract', label: 'supplyContract', type: 'image', base_path: '%env(CONTRACT_PATH)%%env(SUPPLY_PATH)%' }
                    - { property: 'invoice', label: 'invoice', type: 'image', base_path: '%env(CONTRACT_PATH)%%env(INVOICE_PATH)%' }
                    - { property: 'invoiceBack', label: 'invoiceBack', type: 'image', base_path: '%env(CONTRACT_PATH)%%env(INVOICE_BACK_PATH)%' }
                    - { property: 'cif', label: 'cif', type: 'image', base_path: '%env(CONTRACT_PATH)%%env(CIF_PATH)%' }
                    - { property: 'gasInvoice', label: 'gasInvoice', type: 'image', base_path: '%env(CONTRACT_PATH)%%env(GAS_INVOICE_PATH)%' }
                    - { property: 'updatedAt', label: 'updatedAt'}
                    - { property: 'activationDate', label: 'activationDate'}
                    - { property: 'tariff', label: 'tariff'}
                    - { property: 'address', label: 'address'}
                    - { property: 'billingAddress', label: 'billingAddress'}

            edit:
                title: menu.contract
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'externalId', label: 'externalId' }
                    - { property: 'phone', label: 'phone' }
                    - { property: 'mobilePhone', label: 'mobilePhone' }
                    - { property: 'iban', label: 'iban' }
                    - { property: 'email', label: 'email' }
                    - { property: 'status', label: 'status' }
                    - { property: 'user', label: 'user' }
                    - { property: 'ownerDni', label: 'dni'}
                    - { property: 'dniFile', label: 'dni', type: 'vich_image', help: 'image.formats'}
                    - { property: 'dniBackFile', label: 'dniBack', type: 'vich_image', help: 'image.formats'}
                    - { property: 'supplyContractFile', label: 'supplyContract', type: 'vich_image', help: 'image.formats'}
                    - { property: 'invoiceFile', label: 'invoice', type: 'vich_image', help: 'image.formats'}
                    - { property: 'invoiceBackFile', label: 'invoiceBack', type: 'vich_image', help: 'image.formats'}
                    - { property: 'cifFile', label: 'cif', type: 'vich_image', help: 'image.formats'}
                    - { property: 'gasInvoiceFile', label: 'gasInvoice', type: 'vich_image', help: 'image.formats'}
                    - { property: 'updatedAt', label: 'updatedAt'}
                    - { property: 'activationDate', label: 'activationDate'}
                    - { property: 'tariff', label: 'tariff'}
                    - { property: 'product', label: 'product'}
                    - { property: 'address', label: 'address'}
                    - { property: 'billingAddress', label: 'billingAddress'}

            new:
                title: menu.contract
                fields:
                    - { property: 'phone', label: 'phone' }
                    - { property: 'mobilePhone', label: 'mobilePhone' }
                    - { property: 'iban', label: 'iban' }
                    - { property: 'email', label: 'email' }
                    - { property: 'status', label: 'status' }
                    - { property: 'user', label: 'user' }
                    - { property: 'dniFile', label: 'dni', type: 'vich_image', help: 'image.formats'}
                    - { property: 'dniBackFile', label: 'dniBack', type: 'vich_image', help: 'image.formats'}
                    - { property: 'supplyContractFile', label: 'supplyContract', type: 'vich_image', help: 'image.formats'}
                    - { property: 'invoiceFile', label: 'invoice', type: 'vich_image', help: 'image.formats'}
                    - { property: 'invoiceBackFile', label: 'invoiceBack', type: 'vich_image', help: 'image.formats'}
                    - { property: 'cifFile', label: 'cif', type: 'vich_image', help: 'image.formats'}
                    - { property: 'gasInvoiceFile', label: 'gasInvoice', type: 'vich_image', help: 'image.formats'}
                    - { property: 'updatedAt', label: 'updatedAt'}
                    - { property: 'activationDate', label: 'activationDate'}
                    - { property: 'tariff', label: 'tariff'}
                    - { property: 'product', label: 'product'}
                    - { property: 'address', label: 'address'}
                    - { property: 'billingAddress', label: 'billingAddress'}