easy_admin:
    design:    
        menu:
            - { entity: User, icon: 'user' }
            - { entity: Device, icon: 'mobile' }
            - { entity: Notification, icon: 'bell' }
            - { entity: NotificationUser, icon: 'bell' }
            - { label: 'API', route: 'api', icon: 'tasks'}