easy_admin:
    entities:    
        Movement:
            class: App\Entity\Movement
            label: menu.movements
            list:
                title: menu.movements
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'user', label: 'user' }
                    - { property: 'amount', label: 'amount' }
                    - { property: 'concept', label: 'concept' }
                    - { property: 'type', label: 'type' }
                    - { property: 'createdDate', label: 'createdDate' }

            show:
                title: menu.movement
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'user', label: 'user' }
                    - { property: 'amount', label: 'amount' }
                    - { property: 'concept', label: 'concept' }
                    - { property: 'type', label: 'type' }
                    - { property: 'createdDate', label: 'createdDate' }

            edit:
                title: menu.movement
                fields:
                    - { property: 'id', label: 'id' }
                    - { property: 'user', label: 'user' }
                    - { property: 'amount', label: 'amount' }
                    - { property: 'concept', label: 'concept' }
                    - { property: 'type', label: 'type' }
                    - { property: 'createdDate', label: 'createdDate' }
